"""empty message

Revision ID: 14528147d6cb
Revises: b81dd3212f1a
Create Date: 2021-04-21 10:34:01.014119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14528147d6cb'
down_revision = 'b81dd3212f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'user_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.execute(f"UPDATE answers SET user_no = null where user_no=748")

    op.create_unique_constraint(None, 'answers', ['user_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='unique')
    op.alter_column('answers', 'user_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
