"""empty message

Revision ID: 2bae4f431811
Revises: 653ae6419ccc
Create Date: 2021-03-23 20:14:30.159846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bae4f431811'
down_revision = '653ae6419ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_user_id_fkey', 'answers', type_='foreignkey')
    op.drop_constraint('answers_multiple_choice_questions_id_fkey', 'answers', type_='foreignkey')
    op.drop_constraint('answers_scale_questions_id_fkey', 'answers', type_='foreignkey')
    op.drop_column('answers', 'multiple_choice_questions_id')
    op.drop_column('answers', 'scale_questions_id')
    op.drop_column('answers', 'user_id')
    op.create_foreign_key(None, 'multiple_choice_answers', 'answers', ['id'], ['id'])
    op.create_foreign_key(None, 'scale_answers', 'answers', ['id'], ['id'])
    op.create_foreign_key(None, 'screener_answers', 'answers', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'screener_answers', type_='foreignkey')
    op.drop_constraint(None, 'scale_answers', type_='foreignkey')
    op.drop_constraint(None, 'multiple_choice_answers', type_='foreignkey')
    op.add_column('answers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('scale_questions_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('answers', sa.Column('multiple_choice_questions_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('answers_scale_questions_id_fkey', 'answers', 'scale_questions', ['scale_questions_id'], ['id'])
    op.create_foreign_key('answers_multiple_choice_questions_id_fkey', 'answers', 'multiple_choice_questions', ['multiple_choice_questions_id'], ['id'])
    op.create_foreign_key('answers_user_id_fkey', 'answers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
