"""add date fields to uquestions

Revision ID: 487f5cca05c0
Revises: c570b72392a8
Create Date: 2021-05-05 08:44:50.410848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487f5cca05c0'
down_revision = 'c570b72392a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_questions', sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp()))
    op.add_column('u_questions', sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp()))
    u_questions = sa.sql.table("u_questions", sa.Column("created_at", sa.DateTime()))
    op.execute(
        u_questions.update()
        .where(u_questions.c.created_at is None)
        .values(created_at=sa.func.current_timestamp())
    )

    op.create_index(op.f('ix_u_questions_created_at'), 'u_questions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_u_questions_created_at'), table_name='u_questions')
    op.drop_column('u_questions', 'updated_at')
    op.drop_column('u_questions', 'created_at')
    # ### end Alembic commands ###
