"""empty message

Revision ID: 4dd25f3fd41b
Revises: aa943153fb0e
Create Date: 2021-07-11 11:13:17.478047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd25f3fd41b'
down_revision = 'aa943153fb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paystack_transaction', sa.Column('payment_fees', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paystack_transaction', 'payment_fees')
    # ### end Alembic commands ###
