"""empty message

Revision ID: 6af38803f7dd
Revises: 817816fb3c4d
Create Date: 2021-05-13 07:33:29.273976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af38803f7dd'
down_revision = '817816fb3c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('multiple_choice_answers_project_id_fkey', 'multiple_choice_answers', type_='foreignkey')
    op.drop_column('multiple_choice_answers', 'project_id')
    op.drop_constraint('scale_answers_project_id_fkey', 'scale_answers', type_='foreignkey')
    op.drop_column('scale_answers', 'project_id')
    op.drop_constraint('screener_answers_project_id_fkey', 'screener_answers', type_='foreignkey')
    op.drop_column('screener_answers', 'project_id')
    op.drop_constraint('u_answers_project_id_fkey', 'u_answers', type_='foreignkey')
    op.drop_column('u_answers', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_answers', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('u_answers_project_id_fkey', 'u_answers', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('screener_answers', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('screener_answers_project_id_fkey', 'screener_answers', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('scale_answers', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('scale_answers_project_id_fkey', 'scale_answers', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('multiple_choice_answers', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('multiple_choice_answers_project_id_fkey', 'multiple_choice_answers', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
