"""empty message

Revision ID: 7e2167c2da6b
Revises: 822fb43edf6b
Create Date: 2021-05-05 09:23:05.766235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2167c2da6b'
down_revision = '822fb43edf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('paid_projects_project_id_fkey', 'paid_projects', type_='foreignkey')
    op.create_foreign_key(None, 'paid_projects', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paid_projects', type_='foreignkey')
    op.create_foreign_key('paid_projects_project_id_fkey', 'paid_projects', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
