"""empty message

Revision ID: 817816fb3c4d
Revises: 7e2167c2da6b
Create Date: 2021-05-10 21:19:11.686468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817816fb3c4d'
down_revision = '7e2167c2da6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answers', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'project_id')
    # ### end Alembic commands ###
