"""empty message

Revision ID: 822fb43edf6b
Revises: 487f5cca05c0
Create Date: 2021-05-05 09:19:45.037172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822fb43edf6b'
down_revision = '487f5cca05c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scale_answers_project_id_fkey', 'scale_answers', type_='foreignkey')
    op.create_foreign_key(None, 'scale_answers', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scale_answers', type_='foreignkey')
    op.create_foreign_key('scale_answers_project_id_fkey', 'scale_answers', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
