"""empty message

Revision ID: 915118e811e1
Revises: f002010d32b6
Create Date: 2021-04-21 11:00:14.587283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915118e811e1'
down_revision = 'f002010d32b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'user_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('answers_user_no_key', 'answers', type_='unique')
    op.drop_constraint('uq_answers_user_no', 'answers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_answers_user_no', 'answers', ['user_no'])
    op.create_unique_constraint('answers_user_no_key', 'answers', ['user_no'])
    op.alter_column('answers', 'user_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
