"""empty message

Revision ID: 922db00a60bb
Revises: 4dd25f3fd41b
Create Date: 2021-07-11 11:15:36.044693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922db00a60bb'
down_revision = '4dd25f3fd41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paystack_transaction', 'customer_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paystack_transaction', sa.Column('customer_details', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
