"""empty message

Revision ID: aa943153fb0e
Revises: 2ceb8faaa845
Create Date: 2021-07-11 11:11:37.845942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa943153fb0e'
down_revision = '2ceb8faaa845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paystack_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('customer_email', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=64), nullable=True),
    sa.Column('customer_details', sa.String(length=64), nullable=True),
    sa.Column('payment_reference', sa.String(length=64), nullable=True),
    sa.Column('payment_method', sa.String(length=10), nullable=True),
    sa.Column('payment_status', sa.String(length=10), nullable=True),
    sa.Column('gateway_response', sa.String(length=10), nullable=True),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paystack_transaction')
    # ### end Alembic commands ###
