"""empty message

Revision ID: d2ad1e44e86c
Revises: e905c6793ed6
Create Date: 2021-04-17 07:39:39.258488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ad1e44e86c'
down_revision = 'e905c6793ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_answers', sa.Column('answer_option', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_u_answers_answer_option'), 'u_answers', ['answer_option'], unique=False)
    op.drop_index('ix_u_answers_option_five_answer', table_name='u_answers')
    op.drop_index('ix_u_answers_option_four_answer', table_name='u_answers')
    op.drop_index('ix_u_answers_option_one_answer', table_name='u_answers')
    op.drop_index('ix_u_answers_option_three_answer', table_name='u_answers')
    op.drop_index('ix_u_answers_option_two_answer', table_name='u_answers')
    op.drop_column('u_answers', 'option_one_answer')
    op.drop_column('u_answers', 'option_two_answer')
    op.drop_column('u_answers', 'option_five_answer')
    op.drop_column('u_answers', 'option_three_answer')
    op.drop_column('u_answers', 'option_four_answer')
    op.drop_column('u_questions', 'option_two')
    op.drop_column('u_questions', 'option_five')
    op.drop_column('u_questions', 'option_three')
    op.drop_column('u_questions', 'option_one')
    op.drop_column('u_questions', 'option_four')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_questions', sa.Column('option_four', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('u_questions', sa.Column('option_one', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('u_questions', sa.Column('option_three', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('u_questions', sa.Column('option_five', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('u_questions', sa.Column('option_two', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('u_answers', sa.Column('option_four_answer', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('u_answers', sa.Column('option_three_answer', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('u_answers', sa.Column('option_five_answer', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('u_answers', sa.Column('option_two_answer', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('u_answers', sa.Column('option_one_answer', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_u_answers_option_two_answer', 'u_answers', ['option_two_answer'], unique=False)
    op.create_index('ix_u_answers_option_three_answer', 'u_answers', ['option_three_answer'], unique=False)
    op.create_index('ix_u_answers_option_one_answer', 'u_answers', ['option_one_answer'], unique=False)
    op.create_index('ix_u_answers_option_four_answer', 'u_answers', ['option_four_answer'], unique=False)
    op.create_index('ix_u_answers_option_five_answer', 'u_answers', ['option_five_answer'], unique=False)
    op.drop_index(op.f('ix_u_answers_answer_option'), table_name='u_answers')
    op.drop_column('u_answers', 'answer_option')
    # ### end Alembic commands ###
