"""empty message

Revision ID: d97c963df1c6
Revises: 922db00a60bb
Create Date: 2021-07-11 17:49:46.816919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd97c963df1c6'
down_revision = '922db00a60bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payment_amount', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('payment_id', sa.String(length=90), nullable=True))
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'start_date')
    op.drop_column('order', 'session_id')
    op.drop_column('order', 'payment_intent')
    op.drop_column('order', 'delivered')
    op.drop_column('order', 'end_date')
    op.drop_column('order', 'total_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('delivered', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('payment_intent', sa.VARCHAR(length=180), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('session_id', sa.VARCHAR(length=90), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('order', 'payment_id')
    op.drop_column('order', 'payment_amount')
    # ### end Alembic commands ###
