"""add user number field to answer

Revision ID: e95741a38314
Revises: d2ad1e44e86c
Create Date: 2021-04-21 08:13:36.521456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95741a38314'
down_revision = 'd2ad1e44e86c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'user_no')
    # ### end Alembic commands ###
