"""empty message

Revision ID: f002010d32b6
Revises: 14528147d6cb
Create Date: 2021-04-21 10:47:29.246531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f002010d32b6'
down_revision = '14528147d6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'user_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint("uq_answers_user_no", 'answers', ['user_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('answers_user_no_key', 'answers', ['user_no'])
    op.alter_column('answers', 'user_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
